version: 2

jobs:
  build:
    working_directory: ~/EnuwaiAnime
    docker:
      - image: circleci/python:3.8.6
        auth:
          username: b1u3dev
          password: $DOCKERHUB_PASSWORD
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        auth:
          username: b1u3dev
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
        command: |
          sudo pip install pipenv
          pipenv install
      - run:
        command: |
          pipenv run python manage.py test
      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
        destination: tr1

